sudo: required
services:
  - docker

before_install:
  - docker build -t syc1013/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true syc1013/react-test npm test -- --coverage

after_success:
  - docker build -t syc1013/multi-client ./client
  - docker build -t syc1013/multi-nginx ./nginx
  - docker build -t syc1013/multi-server ./server
  - docker build -t syc1013/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push syc1013/multi-client
  - docker push syc1013/multi-nginx
  - docker push syc1013/multi-server
  - docker push syc1013/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-359717375080
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
